from typing import Dict, Iterable, Tuple, TypeVar, TYPE_CHECKING

if TYPE_CHECKING:
  from .diorama import Diorama

T = TypeVar('T')

from .tile import Tile
from lib.version import VERSION

def serialize(diorama: 'Diorama') -> str:
  return '\n'.join(_serialize(diorama))

def _serialize(diorama: 'Diorama') -> Iterable[str]:
  left, top, width, height = diorama.bounds
  eox = width // 2
  eoy = height // 2

  yield 'comments{'
  yield from (f'  {c}' for c in _comments(diorama))
  yield '}'

  yield 'info{'
  yield f'rowcount:{width:d}'
  yield f'colcount:{height:d}'
  yield 'camerapos:Translation: X=2700.000 Y=2700.000 Z=0.000 Rotation: P=44.999989 Y=-89.999992 R=0.000002 Scale X=1.000 Y=1.000 Z=1.000'
  yield 'biome:rock'
  yield 'creator:hognose'
  yield 'spiderrate:10'
  yield 'spidermin:2'
  yield 'spidermax:4'
  yield 'version:2023-08-14-1'
  yield f'opencaves:{_tile_coords(diorama, sorted(diorama.open_cave_flags))}'
  yield '}'

  yield 'tiles{'
  yield from _tile_grid(
    diorama,
    Tile.SOLID_ROCK.export_value,
    dict((k, v.export_value) for (k, v) in diorama.tiles.items()))
  yield '}'

  yield 'height{'
  for _ in range(height + 1):
    yield ''.join('0,' * (width + 1))
  yield '}'

  yield 'resources{'
  yield 'crystals:'
  yield from _tile_grid(diorama, 0, diorama.crystals)
  yield 'ore:'
  yield from _tile_grid(diorama, 0, diorama.ore)
  yield '}'

  yield 'objectives{'
  yield 'resources: 100,0,0'
  yield '}'
  yield 'buildings{'
  yield from (b.serialize((eox, eoy)) for b in diorama.buildings)
  yield '}'
  yield 'landslidefrequency{'
  yield '}'
  yield 'lavaspread{'
  yield '}'
  yield 'miners{'
  yield '}'
  yield 'briefing{'
  yield ''
  yield '}'
  yield 'briefingsuccess{'
  yield ''
  yield '}'
  yield 'briefingfailure{'
  yield ''
  yield '}'
  yield 'vehicles{'
  yield '}'
  yield 'creatures{'
  yield '}'
  yield 'blocks{'
  yield '}'
  yield 'script{'
  yield ''
  yield '}'

def _comments(diorama: 'Diorama') -> Iterable[str]:
  yield 'Cavern generated by Hognose'
  yield 'https://github.com/charredUtensil/hognose'
  yield f'version:{VERSION}'
  yield str(diorama.context)

def _tile_grid(
    diorama: 'Diorama',
    default: T,
    grid: Dict[Tuple[int, int], T]) -> Iterable[str]:
  left, top, width, height = diorama.bounds
  for y in range(top, top + height):
    yield ''.join(
      f'{grid.get((x, y), default)},'
      for x in range(left, left + width))

def _tile_coords(
    diorama: 'Diorama',
    coords: Iterable[Tuple[int, int]]) -> str:
  left, top, _, _ = diorama.bounds
  return ''.join(f'{x - left :d},{y - top :d}/' for x, y in coords)